### PR TITLE
Bump up to 0.3.1

### PR DESCRIPTION
**Pull request by kampersanda**

### CODE REVIEW

**Review by vbkaisetsu — APPROVED** [review]

**Review by vbkaisetsu — COMMENTED** [review]
Does a change of `END_MARKER` affect the serialization result?
If so, the version number should be `0.4.0`.

**Review by vbkaisetsu — CHANGES_REQUESTED** [review]
(dummy comment)

**Comment by kampersanda** [comment]
@vbkaisetsu Yes exactly. It's a critical point. Thank you very much!

**Comment by kampersanda** [comment]
(This PR did not necessarily have to be closed...)

**Pull request closed without merging**
